# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Quiz6' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Quiz6
pod 'Realm'
end
